#ifndef ART_H
#define ART_H

extern Uint16 clr256[];
extern unsigned char stat_bar[];
extern unsigned char stat_compass0[];
extern unsigned char stat_compass1[];
extern unsigned char stat_compass2[];
extern unsigned char stat_bowl[];
extern unsigned char stat_bluedot[];
extern unsigned char stat_reddot[];
extern unsigned char stat_gem[];
extern unsigned char meter_bubble[];
extern unsigned char meter_back[];

#endif
