#ifndef __INCLUDEDfileh
#define __INCLUDEDfileh

void fs_startProgress(int swirly);
void fs_addToProgress(char *filename);
void fs_closeProgress(void);

void fs_init(void);
int fs_open(char *filename);
void fs_read(int fd, char *buf,int n);
void fs_close(int fd);
void fs_getStatus(int *stat,int *ndata);
void fs_execOne(void);

void playWholeCD(void);
void playCDTrack(int track,int repeat);
void stopCD(void);

int getTrackStartFAD(int track);
int getCurrentFAD(void);
int getCurrentStatus(void);

void link(char *filename);

#endif
